version: '3'
services:
   demoAPI_service:
              build: .
              container_name: demoAPI
              ports:
                - "9373:8080"
              volumes:
              - /docker_volumes/appslogs:/logs
              environment:
                 - server.port=8080
                 - EUREKA_PORT=8761
                 - EUREKA_HOST_NAME=eureka-server
                 - DB_HOSTNAME=10.40.2.16
                 - DB_PORT=1521 1521
                 - DB_SID=SPIO spio
                 - DB_USERNAME=spi spi
                 - DB_PASSWORD=test123